gpus:
  - 'a100'
  - 'v100'

include:
- {cuda: '11.5', ubuntu: '18.04', cpu: 'amd64', compiler: {name: 'gcc', version: '8', exe: 'g++'}, gpu_build_archs: ['70', '80'], std: [17]}
- {cuda: '12.1', ubuntu: '22.04', cpu: 'amd64', compiler: {name: 'gcc', version: '9', exe: 'g++'}, gpu_build_archs: ['70', '80'], std: [17]}